favicon: /logo-jiangyu.png
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  icon: flag-cn
  name: 中文

search: true

githubCorner: '<a href="https://github.com/HCLonely/hexo-theme-webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: 测试页面
    icon: far fa-star
    config: testPage
  - name: 常用工具
    icon: far fa-star
    config: hotTools
  - name: 其他工具
    icon: fas fa-tools
    submenu:
      - name: 开发工具
        icon: fas fa-tools
        config: devTools
      - name: 我的博客
        icon: fas fa-blog
        config: myBlog
   - name: 安防行业
    icon: fas fa-shield-alt
    submenu:
      - name: 视频监控
        icon: fas fa-video
        config: video
      - name: 图像传感器
        icon: fas fa-photo-video
        config: sensor
      - name: 处理器DSP
        icon: fas fa-microchip
        config: dsp
      - name: 模组方案商
        icon: fas fa-cube
        config: module
      - name: P2P平台
        icon: fas fa-cloud
        config: P2P
      - name: 系统平台
        icon: fas fa-server
        config: vms
      - name: 系统集成商
        icon: fas fa-square-full
        config: supply
      - name: AI智能算法
        icon: fas fa-dna
        config: AI
      - name: 消费类摄像机
        icon: fas fa-wifi
        config: wifi
      - name: 行业网站
        icon: fas fa-sitemap
        config: sitemap
      - name: 热成像仪
        icon: fas fa-thermometer-full
        config: ir
      - name: 存储
        icon: fas fa-hdd
        config: hdd
      - name: 镜头
        icon: fas fa-circle
        config: lens
      - name: 行业组织
        icon: fas fa-org
        config: org

testPage:
  - name: Child Page
    url: /child
    img: /images/logos/myblog.png
    description: 子页面测试
devTools:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。

hotTools:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。

myBlog:
  - name: HCLonely Blog
    url: https://blog.hclonely.com/
    img: /images/logos/myblog.png
    description: 一个懒人的博客。
video:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。
  - name: 大华
    url: https://www.dahuatech.com/
    img: https://www.dahuatech.com/bocweb/web/img/logo.png
    description: 中国第二大安防视频监控产品提供商。
  - name: 宇视
    url: https://cn.uniview.com/
    img: https://cn.uniview.com/tres/images/Yushi_Site/blue/logo.png
    description: 中国第三大安防视频监控产品提供商。
  - name: Axis
    url: https://www.axis.com/zh-cn
    img: https://www.axis.com/sites/all/themes/axis_bootstrap_subtheme/images/axis_logo.png
    description: 全球第三大安防视频监控产品提供商。

sensor:
  - name: SONY
    url: https://www.sony-semicon.co.jp/e/
    img: https://www.sony-semicon.co.jp/common/images/sony.gif
    description: SONY图像传感器。
  - name: OmniVision
    url: https://www.ovt.com/
    img: https://www.ovt.com/download/sites/14/share.jpg
    description: 中资收购的美国图像传感器品牌。
  - name: 思特威(smartsens)
    url: http://www.smartsenstech.com/
    img: http://www.smartsenstech.com/templates/sitewei/favicon.ico
    description: 中国新兴的从事CMOS图像传感器芯片产品研发、设计及服务的企业。

dsp:
  - name: 华为海思
    url: http://www.hisilicon.com/
    img: http://www.hisilicon.com/Assets/Hisilicon/img/favicon.ico
    description: 华为海思。
  - name: 安霸
    url: https://www.ambarella.com.cn/
    img: https://www.ambarella.com.cn/wp-content/themes/ambarella/img/favicons/favicon.ico
    description: 安霸Ambarella。
  - name: Ingenic-北京君正
    url: http://www.ingenic.com.cn/
    img: http://www.ingenic.com.cn/image/logo.jpg
    description: 北京君正集成电路股份有限公司。
  - name: 国科
    url: http://www.gokemicro.com/
    img: http://www.gokemicro.com/favicon.ico
    description: 国科微电子股份有限公司。
  - name: 富瀚
    url: https://www.fullhan.com/
    img: https://www.fullhan.com/theme/fuhan/images/logo.png
    description: 上海富瀚微电子股份有限公司。
  - name: Nextchip
    url: http://nextchip.com/
    img: http://www.nextchip.com/ch/images/favi_icon.ico
    description: Nextchip.
  - name: Techpoint
    url: http://techpointinc.net/
    img: http://techpointinc.net/images/logo.jpg
    description: Techpoint.
  - name: XM
    url: http://www.xiongmaitech.com/
    img: http://www.xiongmaitech.com/favicon.ico
    description: 雄迈集成电路有限公司。

module:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。

P2P:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。

vms:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。
    
supply:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。    
    
AI:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。  
 
wifi:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。
 
sitemap:
  - name: A&S台湾版
    url: https://www.asmag.com.tw/
    img: https://www.asmag.com/images/asmag.ico
    description: A&S安防知识网台湾版。
  - name: Information Security 資安人科技網
    url: https://www.informationsecurity.com.tw/
    img: https://www.informationsecurity.com.tw/images/info.ico
    description: 台湾安防资讯网站。
ir:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。 
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。 
lens:
  - name: 富士镜头
    url: http://www.fujifilm.com.cn/products/optical_devices/
    img: http://mvlens.fujifilm.com/favicon.ico
    description: 富士镜头。
  - name: 宇瞳镜头
    url: http://www.ytot.cn/
    img: 
    description: 宇瞳镜头。
  - name: Kowa
    url: https://lenses.kowa-usa.com/25-CCTV-Lenses
    img: 
    description: 日本Kowa。
  - name: Computar
    url: https://computar.com/
    img: 
    description: Computar。
  - name: 凤凰镜头
    url: http://www.phenixoptics.com.cn/
    img: 
    description: 凤凰镜头。
  - name: 舜宇光学
    url: http://www.sunnyoptical.com/
    img: 
    description: 舜宇光学。
  - name: Seiko
    url: http://www.seiko-optic.com/seiko/indexcn.html
    img: 
    description: 日本精工镜头。
hdd:
  - name: 海康威视
    url: https://www.hikvision.com
    img: https://www.hikvision.com/etc/clientlibs/it/resources/icons/color-logo.svg
    description: 全球最大的视频安防产品提供商。

org:
  - name: 国际电联
    url: https://www.itu.int/zh/Pages/default.aspx
    img: https://www.itu.int/PublishingImages/masterpage/logos/itu-favicon.ico
    description: 国际电联。   
    
software:
  - name: itellyou
    url: https://next.itellyou.cn/
    img: https://next.itellyou.cn/favicon.ico
    description: 提供可靠的Microsoft原版软件。

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是hexo主题<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>的demo站。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: HCLonely
    url: https://blog.hclonely.com/
    img: /images/logos/myblog.png
    description: 懒人一个
    html: '<br /><blockquote><p>本站是<a href="https://github.com/HCLonely">HCLonely</a>基于<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>项目做的一款<a href="https://hexo.io/">Hexo</a>主题。</p></blockquote>'

since: 2020

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
