favicon: /logo-jiangyu.png
banner: 

logo:
  expanded: /images/logo2021.png
  collapsed: /images/logo-jiangyu.png
  dark: 

flag:
  icon: flag-cn
  name: 中文

search: true


menu:
  - name: 经常光顾
    icon: far fa-star
    config: star
  - name: 独立博客
    icon: fas fa-blog
    config: blog
  - name: 工具资源
    icon: fas fa-tools
    submenu:
      - name: 常用工具
        icon: fas fa-tools
        config: devTools
      - name: 常用软件
        icon: fab fa-uncharted
        config: mysoft
      - name: 资源分享
        icon: fas fa-share
        config: share
  - name: 网站相关
    icon: fab fa-edge
    submenu:
      - name: 建站程序
        icon: fab fa-wordpress
        config: blogsoft
      - name: 建站资源
        icon: fab fa-keycdn
        config: cdn

  - name: 安防行业
    icon: fas fa-shield-alt
    submenu:
      - name: 安防工具
        icon: fas fa-tools
        config: cctvtools
      - name: 视频监控
        icon: fas fa-video
        config: video
      - name: 图像传感器
        icon: fas fa-photo-video
        config: sensor
      - name: 处理器DSP
        icon: fas fa-microchip
        config: dsp
      - name: 模组方案商
        icon: fas fa-cube
        config: module
      - name: P2P物联网平台
        icon: fas fa-cloud
        config: P2P
      - name: 系统平台
        icon: fas fa-server
        config: vms
      - name: 系统集成商
        icon: fas fa-square-full
        config: supply
      - name: AI智能算法
        icon: fas fa-dna
        config: AI
      - name: 消费类摄像机
        icon: fas fa-wifi
        config: wifi
      - name: 行业网站
        icon: fas fa-sitemap
        config: sitemap
      - name: 热成像仪
        icon: fas fa-temperature-high
        config: ir
      - name: 存储
        icon: fas fa-hdd
        config: hdd
      - name: 镜头
        icon: fas fa-circle
        config: lens
      - name: 行业组织
        icon: fas fa-sitemap
        config: org
star:
  - name: 视听资源
    url: https://dropbox.jiangyu.org/
    img: /images/logos/dropbox.png
    description: 存储于阿里云网盘的视听资源。
  - name: 分享资源
    url: https://box.jiangyu.org/
    img: /images/logos/box.png
    description: 存储于各大网盘的资源。
  - name: 少数派
    url: https://sspai.com/
    img: /images/logos/sspai.ico
    description: 高效工作，品质生活。
  - name: 爱范儿ifanr
    url: https://www.ifanr.com
    img: /images/logos/ifanr.ico
    description: 让未来触手可及。

share:
  - name: 视听资源
    url: https://dropbox.jiangyu.org/
    img: /images/logos/dropbox.png
    description: 存储于阿里云网盘的视听资源。
  - name: 分享资源
    url: https://box.jiangyu.org/
    img: /images/logos/box.png
    description: 个人存储于各大网盘的资源。
  - name: 书格
    url: https://www.shuge.org/
    img: /images/logos/shuge.png
    description: 高品质的古籍，书画等资源。

devTools:
  - name: Wetransfer
    url: https://wetransfer.com/
    img: /images/logos/wt.png
    description: 短期文件存储分享网站。
  - name: 奶牛快传
    url: https://cowtransfer.com/
    img: /images/logos/ct.png
    description: 国内山寨wetransfer的网站。
  - name: 在线PS
    url: https://ps.gaoding.com/
    img: /images/logos/ps.ico
    description: 在外面偶尔需要PS，但是电脑没装软件，可以使用网页版的在线PS。
  - name: 百度脑图
    url: https://naotu.baidu.com/
    img: /images/logos/baidunaotu.ico
    description: 百度脑图，便捷的脑图编辑工具- 免安装 云存储。
  - name: smallpdf
    url: https://smallpdf.com/cn
    img: /images/logos/smallpdf.png
    description: 功能一应俱全、简单好用的线上 PDF 工具。
  - name: unsplash
    url: https://unsplash.com/
    img: /images/logos/unsplash.png
    description: 免费版权的图片素材网站。
  - name: Flowchart Maker &amp; Online Diagram Software
    url:  https://app.diagrams.net/
    img: /images/logos/diagrams.png
    description: 在线画网络拓扑图，流程图。
  - name: 去不图床
    url:  https://7bu.top/
    img: /images/logos/7bu.ico
    description: 去不图床。
  - name: SM.MS
    url:  https://sm.ms/
    img: /images/logos/smms.ico
    description: SM.MS图床，loli图床。
  - name: APK下载
    url:  https://apkdl.in/
    img: /images/logos/apkdl.ico
    description: 下载apk安装包。
  - name: 语雀
    url:  https://www.yuque.com/
    img: /images/logos/yuque.png
    description: 阿里巴巴出品的云端知识库工具。
  - name: FND
    url:  https://fnd.io/
    img: /images/logos/fnd.png
    description: 搜素ios app。

mysoft:
  - name: itellyou
    url: https://next.itellyou.cn/
    img: /images/logos/itellu.ico
    description: 提供可靠的Microsoft原版软件。
  - name: 小众软件
    url: https://www.appinn.com/
    img: /images/logos/appinn.png
    description: 分享免费、小巧、实用、有趣、绿色的软件。

blogsoft:
  - name: WordPress
    url: https://wordpress.org/
    img: /images/logos/wordpress.ico
    description: Blog Tool, Publishing Platform, and CMS.
  - name: Typecho
    url: http://typecho.org/
    img: /images/logos/typecho.ico
    description: PHP+Mysql的博客程序。
  - name: ZBlog
    url: https://www.zblogcn.com/
    img: /images/logos/zblog.ico
    description: 开源免费、小巧强大的博客程序与CMS建站系统。
  - name: Tipask
    url: https://wenda.tipask.com/questions
    img: /images/logos/tipask.ico
    description: PHP问答系统,Tipask问答系统。
  - name: Flarum
    url: https://discuss.flarum.org/
    img: /images/logos/flarum.png
    description: 优雅简洁的轻论坛系统。
    
cdn:
  - name: jsDelivr
    url: https://www.jsdelivr.com/
    img: /images/logos/jsdelivr.png
    description: A free, fast, and reliable CDN for open source.
  - name: iconfont
    url: https://www.iconfont.cn/
    img: /images/logos/iconfont.ico
    description: iconfont-阿里巴巴矢量图标库。
  - name: 字节跳动静态资源公共库
    url: https://cdn.bytedance.com/
    img: /images/logos/bytedance.png
    description: 同步自cdnjs，支持多协议、资源动态拼接、快速检索及资源的动态更新。
    
cctvtools:
  - name: 海康安防计算器
    url: https://h5proxy.hikvision.com/jf/videocal/index.html#/
    img: /images/logos/hik.ico
    description: 海康安防计算器。
  - name: 大华安防计算器
    url: https://www.dahuatech.com/support/work/#/home
    img: /images/logos/dahuatech.ico
    description: 大华安防计算器。
  - name: Axis镜头选型计算
    url: https://www.axis.com/en-us/tools/lens-calculator
    img: /images/logos/axis.ico
    description: Axis镜头选型计算工具。
  - name: Axis工具
    url: https://www.axis.com/en-us/tools
    img: /images/logos/axis.ico
    description: Axis工具
  - name: JVSG
    url: http://cn.jvsg.com/
    img: /images/logos/jvsg.png
    description: 功能比较强大的安防视频监控设计工具软件，但是是收费的。
  - name: imatest
    url: https://www.imatest.com/
    img: /images/logos/imatest.ico
    description: 图像质量分析软件。

video:
  - name: 海康威视
    url: https://www.hikvision.com
    img: /images/logos/hik.ico
    description: 全球最大的视频安防产品提供商。
  - name: 大华
    url: https://www.dahuatech.com/
    img: /images/logos/dahuatech.ico
    description: 中国第二大安防视频监控产品提供商。
  - name: 宇视
    url: https://cn.uniview.com/
    img: /images/logos/uniview.ico
    description: 中国第三大安防视频监控产品提供商。
  - name: Axis
    url: https://www.axis.com/zh-cn
    img: /images/logos/axis.ico
    description: 全球第三大安防视频监控产品提供商。

sensor:
  - name: SONY
    url: https://www.sony-semicon.co.jp/e/
    img: /images/logos/sony.ico
    description: SONY图像传感器。
  - name: OmniVision
    url: https://www.ovt.com/
    img: /images/logos/ovt.jpg
    description: 中资收购的美国图像传感器品牌。
  - name: 思特威(smartsens)
    url: http://www.smartsenstech.com/
    img: /images/logos/smartsenstech.ico
    description: 中国新兴的从事CMOS图像传感器芯片产品研发、设计及服务的企业。
  - name: 格科微
    url: https://www.gcoreinc.com/
    img: /images/logos/gc.png
    description: 位于上海的CMOS厂家，产品型号以GC开头。
  - name: 晶相光电
    url: https://www.soinc.com.tw/
    img: /images/logos/soinc.png
    description: 台湾CMOS厂家，产品型号以F,H,K,Q等命名。
  - name: 原相
    url: https://www.pixart.com/
    img: /images/logos/pix.png
    description: 台湾CMOS厂家，产品型号以PS开头。
  - name: Aptina
    url: https://www.onsemi.cn/products/sensors/image-sensors
    img: /images/logos/aptina.png
    description: 被安森美收购，产品型号以AR开头。

dsp:
  - name: 华为海思
    url: http://www.hisilicon.com/
    img: /images/logos/hisilicon.ico
    description: 华为海思。
  - name: 安霸
    url: https://www.ambarella.com.cn/
    img: /images/logos/amba.ico
    description: 安霸Ambarella。
  - name: Ingenic-北京君正
    url: http://www.ingenic.com.cn/
    img: /images/logos/ig.png
    description: 北京君正集成电路股份有限公司。
  - name: 国科
    url: http://www.gokemicro.com/
    img: /images/logos/guoke.ico
    description: 国科微电子股份有限公司。
  - name: 富瀚
    url: https://www.fullhan.com/
    img: /images/logos/fullham.ico
    description: 上海富瀚微电子股份有限公司。
  - name: Nextchip
    url: http://nextchip.com/
    img: /images/logos/nextchip.ico
    description: Nextchip.
  - name: Techpoint
    url: http://techpointinc.net/
    img: /images/logos/techpoint.jpg
    description: TVI摄像机方案
  - name: XM
    url: http://www.xiongmaitech.com/
    img: /images/logos/xm.ico
    description: 雄迈，XM550,XM530 IPC方案，XM330/350/380 XVI摄像机方案
  - name: 安凯
    url: http://www.anyka.com/
    img: /images/logos/anyka.png
    description: 消费类摄像机芯片，AK39E系列。
  - name: Mstar晨星
    url: https://www.mstarsemi.com/
    img: /images/logos/mstar.ico
    description: 联发科收购。
  - name: 星宸SigmaStar
    url: http://www.sigmastarsemi.com/
    img: /images/logos/ss.png
    description: Mstar晨星关联公司。
  - name: 智源/升迈(NovaTek)
    url: https://www.novatek.com.tw/zh-CN/Home/Index
    img: /images/logos/nov.ico
    description: 联咏收购。
  - name: 瑞昱Realtek
    url: https://www.realtek.com/zh/
    img: /images/logos/rtk.ico
    description: 代表产品3903N，消费类。
  - name: 瑞芯微
    url: https://www.rock-chips.com/
    img: /images/logos/rk.ico
    description: 代表产品RV1109,RV1126。

module:
  - name: 天视通
    url: http://tpsee.com/
    img: /images/logos/topsee.ico
    description: 天视通,topsee,seetong,网络摄像机模组。
  - name: 雄迈
    url: http://www.xiongmaitech.com/
    img: /images/logos/xm.ico
    description: 雄迈摄像机，DVR，NVR模组。
  - name: 安佳威视
    url: http://www.anjvision.com/
    img: /images/logos/anj.ico
    description: 源自天视通的模组厂家，以Mstar晨星，星宸SigmaStar方案为主。
  - name: 中维尚维
    url: http://www.sunywo.com/cn/index.shtml
    img: /images/logos/sunywo.ico
    description: 与雄迈类似的摄像机,DVR,NVR模组厂家。
  - name: 瀚晖
    url: http://www.hankvision.com/
    img: /images/logos/hank.ico
    description: 网络一体化机芯。
  - name: 捷高
    url: http://www.cnjabsco.com/
    img: /images/logos/jco.png
    description: 网络摄像机,NVR模组。

P2P:
  - name: UMEye
    url: http://www.umeye.com/
    img: /images/logos/umeye.ico
    description: UMEye。
  - name: 大拿Danale
    url: https://intl.danale.com/
    img: /images/logos/danale.png
    description: danale。
  - name: 浪涛
    url: http://www.vnow.cn/index.html
    img: /images/logos/vnow.png
    description: goolink。
  - name: 涂鸦智能
    url: https://www.tuya.com/
    img: /images/logos/tuya.ico
    description: Smart life,tuya。
  - name: 探鸽
    url: https://tange.ai/
    img: /images/logos/tange.png
    description: iCam365。

vms:
  - name: 泰辰，致精
    url: http://www.unisight.com.cn/cn/index.html
    img: /images/logos/taichen.ico
    description: 泰辰，致精，unisight。
  - name: 中盛益华
    url: http://www.csvision.cn/
    img: /images/logos/csv.ico
    description: 中盛益华。
  - name: Genetec
    url: https://www.genetec.com/
    img: /images/logos/genetec.png
    description: Genetec的是一家安防视频监控软件开发公司成立于1997年，总部设在加拿大。
  - name: Milestone Systems
    url: https://www.milestonesys.com/
    img: /images/logos/milestonesys.ico
    description: Milestone Systems成立于1998年，视频监控管理软件行业的领导者。
  - name: Motorola Solutions
    url: https://www.motorolasolutions.com/
    img: /images/logos/motorola.ico
    description: 摩托罗拉系统，2011年由摩托罗拉公司分拆而来，核心市场是公共安全政府机构和商业企业。
    
supply:
  - name: 高新兴
    url: http://www.gosuncn.com/
    img: /images/logos/gosun.ico
    description: 全球领先的智慧城市物联网产品与服务提供商。
  - name: 佳都
    url: https://www.pcitech.com/en/index.html
    img: /images/logos/pci.ico
    description: 全球领先的智慧城市物联网产品与服务提供商。  
    
AI:
  - name: 商汤
    url: https://www.sensetime.com/cn
    img: /images/logos/sense.ico
    description: 商汤。  
  - name: 依图
    url: https://www.yitutech.com/
    img: /images/logos/yitu.ico
    description: 依图。
  - name: 云从
    url: https://www.cloudwalk.com/
    img: /images/logos/cloudwalk.png
    description: 云从。
  - name: 旷视
    url: https://www.megvii.com/
    img: /images/logos/mg.ico
    description: 旷视。
 
wifi:
  - name: 超级看看
    url: http://www.xiongmaitech.com/
    img: /images/logos/icsee.png
    description: 雄迈，超级看看，icsee，监控眼
  - name: V380
    url: http://www.av380.cn/
    img: /images/logos/av380.png
    description: 广州宏视，V380
  - name: 萤石
    url: https://www.ys7.com/
    img: /images/logos/ys7.ico
    description: 海康萤石
  - name: 乐橙
    url: https://cn.imoulife.com/web/
    img: /images/logos/lechange.ico
    description: 大华乐橙
    
sitemap:
  - name: A&S台湾版
    url: https://www.asmag.com.tw/
    img: /images/logos/as.ico
    description: A&S安防知识网台湾版。
  - name: Information Security 資安人科技網
    url: https://www.informationsecurity.com.tw/
    img: /images/logos/asis.ico
    description: 台湾安防资讯网站。
  - name: A&S mag
    url: https://www.asmag.com/
    img: /images/logos/as.ico
    description: The comprehensive security industry platform
    
ir:
  - name: Teledyne FLIR
    url: https://www.flir.cn/
    img: /images/logos/flir.ico
    description: 菲力尔，世界第六感。 
  - name: 大立科技
    url: https://www.dali-tech.com/
    img: /images/logos/dali.ico
    description: 专业红外热像仪,红外热成像,红外测温仪,人体测温仪厂家。 
  - name: 优利德(UNI-T)
    url: https://www.uni-trend.com.cn/
    img: /images/logos/uni.ico
    description: 红外热像仪，红外测温仪，红外热成像。 
  - name: 朗驰欣创
    url: http://www.launchdigital.net/
    img: /images/logos/launchdigital.ico
    description: 红外线测温仪，红外热成像设备，巡检机器人。 
    
lens:
  - name: 富士镜头
    url: http://www.fujifilm.com.cn/products/optical_devices/
    img: /images/logos/fuji.ico
    description: 富士镜头。
  - name: 宇瞳镜头
    url: http://www.ytot.cn/
    img: /images/logos/ytot.ico
    description: 宇瞳镜头。
  - name: Kowa
    url: https://lenses.kowa-usa.com/25-CCTV-Lenses
    img: /images/logos/kowa.ico
    description: 日本Kowa。
  - name: Computar
    url: https://computar.com/
    img: /images/logos/computar.ico
    description: Computar。
  - name: 凤凰镜头
    url: http://www.phenixoptics.com.cn/
    img: /images/logos/phenix.png
    description: 凤凰镜头。
  - name: 舜宇光学
    url: http://www.sunnyoptical.com/
    img: /images/logos/sunny.ico
    description: 舜宇光学。
  - name: Seiko
    url: http://www.seiko-optic.com/seiko/indexcn.html
    img: /images/logos/seiko.jpg
    description: 日本精工镜头。
    
hdd:
  - name: 希捷
    url: https://www.seagate.com/cn/zh/
    img: /images/logos/seagate.ico
    description: Seagate。
  - name: 西数
    url: https://www.westerndigital.com/zh-cn
    img: /images/logos/wd.ico
    description: Western Digital。
    
org:
  - name: 国际电联
    url: https://www.itu.int/zh/Pages/default.aspx
    img: /images/logos/itu.ico
    description: 国际电联。
  - name: ONVIF
    url: https://www.onvif.org/
    img: /images/logos/onvif.png
    description: ONVIF 
  - name: PSIA
    url: https://psialliance.org/
    img: /images/logos/psia.gif
    description: 物理安防互操作性联盟,Physical Security Interoperability Alliance
  - name: AOMedia
    url: https://aomedia.org/
    img: /images/logos/av.png
    description: Alliance for Open Media,AV1,AV2视频编码
  - name: WebRTC
    url: https://webrtc.org/
    img: /images/logos/webrtc.png
    description: web that enables Real-Time Communications (RTC)

about:
  url: https://www.jiangyu.org/
  icon: far fa-heart
  name: 关于本站


since: 2020

busuanzi:
  enable: true
  position: footer # 'footer','sidebar'
  pv: 本站总访问量 $pv
  uv: 本站总访客数 $uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://cdn.jsdelivr.net/npm/busuanzi@2.3.0/bsz.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
